version: '3'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn fetch'
    environment:
      DATABASE_URL: postgresql://krakenite:asuperstrongpassword@db:5432/staking?search_path=public
    depends_on:
      - db

  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=krakenite
      - POSTGRES_PASSWORD=asuperstrongpassword
      - POSTGRES_DB=staking
    ports:
      - "1337:5432"
    volumes:
    - ./bdd/pg:/var/lib/postgresql/data
